#ifndef PACKETTYPE_H
#define PACKETTYPE_H

typedef enum {
    PACKET_TYPE_NONE = 0,
    PACKET_TYPE_HELLO = 1,
    PACKET_TYPE_TASK_ASSIGN = 2,
    PACKET_TYPE_TASK_RESULT = 3,
    PACKET_TYPE_STATUS_UPDATE = 4,
    PACKET_TYPE_CLIENT_CAPABILITIES = 5,
    PACKET_TYPE_TASK_REQUEST = 6,
    PACKET_TYPE_MISSING_INFO = 7,
    PACKET_TYPE_ACKNOWLEDGE = 8,
    PACKET_TYPE_TASK_REJECT = 9,
    PACKET_TYPE_TASK_NONE_AVAILABLE = 10
} PacketType;

#endif
